// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate / db push) için — schema engine pgbouncer üzerinden çalışmaz,
    // bu yüzden session pooler URL'i kullanılır. Runtime Prisma Client ise DATABASE_URL'i
    // `src/lib/prisma.ts` içinde env'den doğrudan okur (bu config'ten bağımsız).
    url: process.env["DIRECT_URL"],
    // Prisma 7'de `--shadow-database-url` CLI flag'i kaldırıldı; migrate diff/dev için
    // shadow DB URL'i config'te tanımlanmalı. CI'da SHADOW_DATABASE_URL env'den okunur.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
